# Generated by Django 5.1.1 on 2024-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.TextField(max_length=255)),
                ('idade_usuario', models.IntegerField()),
            ],
        ),
    ]
